/*
 EasyRecipe PLUS 3.2.2708 Copyright (c) 2014 BoxHill LLC
*/
window.EASYRECIPE=window.EASYRECIPE||{};
(function(a){function Q(){var h,b,l,n,g,d,f,e=I.selection.getNode();h=a(".ERGPAlignment input:radio[name=rbERGPAlign]:checked").val();b=a(".ERGPSize input:radio[name=rbERGPSize]:checked").val();d=a.trim(t.val());f=a.trim(u.val());l=a.trim(v.val());n=""===l?"none":"custom";if(k.isEntryDialog){for(b in c.meta.sizes)c.meta.sizes.hasOwnProperty(b)&&(c.meta.sizes[b].url=c.baseurl+c.meta.sizes[b].file);d={sizes:c.meta.sizes};h={size:b,align:h,link:n,linkUrl:l};k.insertUploadedImage(d,h)}else if("full"===
b?(l=c.meta.width,n=c.meta.height,g=c.meta.file):(l=c.meta.sizes[b].width,n=c.meta.sizes[b].height,g=c.meta.sizes[b].file),b=("aligncenter"===h?'<p style="text-align:center">':"")+('<img class="'+h+" size-"+b+" wp-image-"+c.id+'"'),b+=' title="'+d+'"',b+=' alt="'+f+'"',b+=' width="'+l+'"',b+=' height="'+n+'"',b+=' src="'+c.baseurl+g+'"',b+=" />",b+="aligncenter"===h?"</p>":"","#document"===e.nodeName&&(e=a("body",m)[0]),"BODY"===e.nodeName.toUpperCase())a(e).hasClass("mceContentBody")||(e=a("body",
m)[0]),a(e).append("&nbsp;"+b);else{for(;e.parentNode&&"BODY"!==e.parentNode.nodeName.toUpperCase();)e=e.parentNode;e.parentNode?"DIV"===e.nodeName.toUpperCase()||"SPAN"===e.nodeName.toUpperCase()?a(e,m).after(b):a(e,m).before(b):(e=a("body",m)[0],a(e).append(b))}p.dialog("close")}function R(c,b,l){w=!1;typeof tinyMCE!==S&&tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden()&&(w=!0);w?(I=tinyMCE.activeEditor,m=b.editorId===x?a("#"+x+"_ifr").contents():a("#mce_fullscreen_ifr").contents()):alert("You must use the Visual Editor to add or update an EasyRecipe")}
function T(){var h="html5,flash,silverlight,html4";y.hide();z.hide();q.show();A.show();B.text("");t.val("");u.val("");v.val("");p.dialog(U);r.hide();a("#ERGPplupload").html("");plupload.VERSION&&plupload.ua&&"1.5.4"==plupload.VERSION&&plupload.ua.gecko&&(h="flash,silverlight,html4");d=new plupload.Uploader({runtimes:h,browse_button:"btnERGPSelect",max_file_size:"10mb",container:"easyrecipeUpload",url:ajaxurl,flash_swf_url:k.wpurl+"/wp-includes/js/plupload/plupload.flash.swf",silverlight_xap_url:k.wpurl+
"/wp-includes/js/plupload/plupload.silverlight.xap",multipart_params:{postID:J,action:"easyrecipeUpload"},filters:[{title:"Image files",extensions:"jpg,gif,png"}]});d.init();d.bind("FilesAdded",function(a,c){B.text("File: "+c[0].name);C.text(0);s.show();q.hide();y.show();d.start()});d.bind("UploadProgress",function(a,c){C.text(c.percent);s.progressbar("value",c.percent);100===c.percent&&r.show()});d.bind("Error",function(a,c){a.refresh()});d.bind("FileUploaded",function(b,h,d){var g;c=a.parseJSON(d.response);
A.hide();z.show();c.meta.sizes.thumbnail?(b=c.meta.sizes.thumbnail.file,h=c.meta.sizes.thumbnail.width,d=c.meta.sizes.thumbnail.height):(b=c.meta.file,d=c.meta.height,h=c.meta.width);D.attr("src",c.baseurl+b);D.css("top",Math.floor((140-130*d/h)/2));c.postID&&a('.ERGuestPost form input[name="postID"]').val(c.postID);for(g in f)f.hasOwnProperty(g)&&(b=f[g],c.meta.sizes[g]?(b.attr(E,!1),b.next("span").text(" ("+c.meta.sizes[g].width+" x "+c.meta.sizes[g].height+")")):(b.attr(E,!0),b.next("span").text("")));
f.medium.attr(E)?F.attr(K,!0):f.medium.attr(K,!0);L.text(" ("+c.meta.width+" x "+c.meta.height+")");g=c.meta;a("#divERGPFIName").text(g.file);a("#divERGPFIDim").text(g.width+" x "+g.height);a("#divERGPFISize").text(g.filesize);r.hide()});d.refresh()}function V(){var c,b,d,f=!1;c=a("#spnERGPNameErr");b=a("#spnERGPURLErr");d=a("#spnERGPEmailErr");c.text("");b.text("");b.text("");""===a.trim(M.val())&&(c.text("You must enter your name"),f=!0);""===a.trim(G.val())?(d.text("You must enter your email"),
f=!0):W.test(a.trim(G.val()))||(d.text("You must enter a valid email address"),f=!0);""===a.trim(N.val())&&(b.text("You must enter your website URL"),f=!0);f||(O.hide(),P.show())}var p,U="open",S="undefined",q,s,m,x,I,w,J,d=null,z,A,y,B,c,t,u,v,f={},F,L,H,E="disabled",K="checked",O,P,M,G,N,k,C,D,r,W=/[a-z0-9!#$%&'*+\/=?\^_`{|}~\-]+(?:\.[a-z0-9!#$%&'*+\/=?\^_`{|}~\-]+)*@(?:[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?/i;a(function(){var c;k=EASYRECIPE;p=a("#easyrecipeUpload");
H=a("#easyrecipeLinks");p.dialog({autoOpen:!1,width:500,height:600,title:"Upload an image",modal:!0,appendTo:k.dialogs,dialogClass:"easyrecipeUpload",close:function(){a(".easyrecipeUpload").filter(function(){return""===a(this).text()}).remove();d&&(d.destroy(),d=null)},open:function(){q.show();s.progressbar("value",0)}});a('input[type="button"]',H).button();H.dialog({autoOpen:!1,width:480,title:"Insert/edit link",modal:!0,dialogClass:"easyrecipeLinks",appendTo:k.dialogs,close:function(){a(".easyrecipeLinks").filter(function(){return""===
a(this).text()}).remove()},open:function(){}});z=a("#divERGPUploaded");A=a("#divERGPUploadContainer");y=a("#divERGPUploading");B=a("#divERGPFile");t=a("#inpERGPTitle");u=a("#inpERGPAltText");v=a("#inpERGPLinkURL");q=a("#btnERGPSelect").button();a("#cbERGPLTarget");a("#fldERGPLTitle");a("#fldERGPLURL");P=a("#divERGPPost");O=a("#divERGPData");M=a("#fldERGPName");G=a("#fldERGPEmail");N=a("#fldERGPURL");f.thumbnail=a('.ERGPSize input[value="thumbnail"]');f.medium=a('.ERGPSize input[value="medium"]');
f.large=a('.ERGPSize input[value="large"]');F=a('.ERGPSize input[value="full"]');L=F.next("span");a("#btnERGPInsert").button().on("click",Q);s=a("#divERGPProgress").progressbar().hide();a(window).bind("guestpostloaded",R);a(".wp-media-buttons").hide();J=a("#ERGPpostID").val();x=a(".wp-editor-wrap").attr("id").replace(/^wp-(.*)-wrap$/ig,"$1");a(".ERGuestPost .ERGPButton").button();a("#btnERGPContinue").on("click",V);D=a("#imgERGPThumb");C=a("#spnERGComplete");r=a("#divERGPSpinner");k.isGuest=!0;k.doUpload=
T;if(c=a("#inpERGPAuthor").val())k.author='"'+c+'"'})})(jQuery);
