/*
 EasyRecipe PLUS 3.2.2708 Copyright (c) 2014 BoxHill LLC
*/
window.EASYRECIPE=window.EASYRECIPE||{};EASYRECIPE.widget=EASYRECIPE.widget||jQuery.widget;EASYRECIPE.button=EASYRECIPE.button||jQuery.fn.button;
(function(a){function Jb(a,c){Xa.show();da.hide();Ya.show();switch(c.newTab?c.newTab.index():c.index){case 0:da.css("right","10px");da.show();break;case 3:da.css("right","inherit");Ya.hide();da.show();break;case 4:Xa.hide()}}function Za(){Ea.off("change",Za);Y=!0}function g(a){return a?(a+"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&nbsp;/g," "):""}function ea(d){return d?a("<div />").text(d).html():""}function n(d){return a.trim(ea(d.val()))||!1}function Kb(a,c){var b=
Fa.tabs("option","active");Fa.tabs("option","active",++b)}function v(a){var c,b=/\[img +(.*?) *\/?\]/i,f=/\[url ([^\]]+)\](.*?\[\/url\])/i;for(c=b.exec(a);null!==c;)Z.push(c[1]),a=a.replace(b,"[img:"+Z.length+"]"),c=b.exec(a);for(c=f.exec(a);null!==c;)G.push(c[1]),a=a.replace(f,"[url:"+G.length+"]$2"),c=f.exec(a);return a}function w(a){var c,b=/\[img:(\d+)\]/i,f=/\[url:(\d+)\](.*?)\[\/url\]/i;for(c=b.exec(a);null!==c;)c=Z[c[1]-1],a=a.replace(b,"[img "+c+"]"),c=b.exec(a);for(c=f.exec(a);null!==c;)c=
G[c[1]-1],a=a.replace(f,"[url "+c+"]$2[/url]"),c=f.exec(a);return a}function sb(a,c){var b,f,e,k=0,t="",l,g,h,q,p;b=a;for(c=c||{};;){e=b.length;f=b.indexOf("#",k);-1!==f&&(e=f,l=0);f=b.indexOf("\x3c!-- START REPEAT ",k);-1!==f&&f<e&&(e=f,l=1);f=b.indexOf("\x3c!-- START INCLUDEIF ",k);-1!==f&&f<e&&(e=f,l=2);if(e===b.length)return t+b.substr(k);f=e-k;t+=b.substr(k,f);k=e;switch(l){case 2:e=b.substr(k,44);e=Lb.exec(e);if(null!==e)f=e[1],g="!"!==f,h=e[2];else break;q="\x3c!-- END INCLUDEIF "+f+h+" --\x3e";
e=q.length;q=b.indexOf(q);if(-1===q){k++;break}p=typeof c[h]!==na&&!1!==c[h];p===g?(f="\x3c!-- START INCLUDEIF "+f+h+" --\x3e",f=f.length,b=b.substr(0,k)+b.substr(k+f,q-k-f)+b.substr(q+e)):b=b.substr(0,k)+b.substr(q+e);break;case 0:e=b.substr(k,22);e=Mb.exec(e);if(null===e){t+="#";k++;continue}e=e[1];if(""!==c[e]&&!c[e]){t+="#"+e+"#";k+=e.length+2;continue}t+=c[e];k+=e.length+2;break;case 1:e=b.substr(k,45);e=Nb.exec(e);if(null===e){t+="<";k++;continue}e=e[1];if(!(c[e]&&c[e]instanceof Array)){t+=
"<";k++;continue}k+=e.length+22;f=b.indexOf("\x3c!-- END REPEAT "+e+" --\x3e",k);if(-1===f){t+="\x3c!-- START REPEAT "+e+" --\x3e";continue}g=f-k;q=b.substr(k,g);h=c[e];for(f=0;f<h.length;f++)t+=sb(q,h[f]);k+=e.length+g+20}}}function Ga(d){var c=a.trim(d.val()),b=0,f=0;$a.hide();if(""===c)return!0;m=ab.exec(c);if(null===m){m=Ob.exec(c);if(null===m)return $a.show(),!1;b=0;f=m[1]}else b=m[1]?parseInt(m[1],10):0,f=m[2]?parseInt(m[2],10):0;0===b&&0===f?d.val(""):(c=0<b?b+" hour":"",1<b&&(c+="s"),b=0<
f?f+" min":"",1<f&&(b+="s"),d.val(a.trim(c+" "+b)));return!0}function tb(d){var c,b,f="";for(c=0;c<d.length;c++)b=d[c],3===b.nodeType?(b=a.trim(b.nodeValue),""!==b&&(f+=b+"\n")):1===b.nodeType&&0<b.childNodes.length&&(f+=tb(b.childNodes));return f}function ub(){var d;a(bb,p).remove();d=H.selection.getNode();"#document"===d.nodeName&&(d=oa[0]);if("BODY"===d.nodeName.toUpperCase())a(d).hasClass("mceContentBody")||(d=oa[0]),a(d).append("&nbsp;"+Ha);else{for(;d.parentNode&&"BODY"!==d.parentNode.nodeName.toUpperCase();)d=
d.parentNode;d.parentNode?"DIV"===d.nodeName.toUpperCase()||"SPAN"===d.nodeName.toUpperCase()?a(d,p).after(Ha):a(d,p).before(Ha):(d=oa[0],a(d).append("&nbsp;"+Ha))}fa=-1;return a(bb,p)}function Pb(a,c,b){}function Qb(d){switch(d.type){case "js":a("head").append(a('<script type="text/javascript">'+d.js+"\x3c/script>"));s[d.f]();break;case "html":a(d.dest).html(d.html)}}function Rb(){Ia.unbind(O);Ja.unbind(O);I.dialog(J);cb=!0;db()}function Sb(d,c){var b,f="",e;e=d.recipe;"success"!==c&&(I.dialog(J),
cb=!0,db());R.val(g(e.recipe_title));e.rating&&a.isNumeric(e.rating)&&pa.val(e.rating);z=e.recipe_image;S.val("");e.author?E.val(g(e.author)):E.val("");$.val(e.cuisine||"");S.val(e.mealType||"");eb.val("");T.val(g(e.summary));m=vb.exec(e.prep_time);null!==m?(b=m[1]?m[1]+"h ":"",A.val(b+m[2]+"m")):A.val(g(e.prep_time));m=vb.exec(e.cook_time);null!==m?(b=m[1]?m[1]+"h ":"",B.val(b+m[2]+"m")):B.val(g(e.cook_time));aa.val(g(e.yield));ga.val(g(e.serving_size));e.nutrition?(b=e.nutrition,ha.val(g(b.calories)),
ia.val(g(b.totalFat)),qa.val(g(b.saturatedFat)),ra.val(g(b.unsaturatedFat)),sa.val(g(b.transFat)),ta.val(g(b.totalCarbohydrates)),ua.val(g(b.sugars)),va.val(g(b.sodium)),wa.val(g(b.dietaryFiber)),xa.val(g(b.protein)),ya.val(g(b.cholesterol))):(ha.val(g(e.calories)),ia.val(g(e.fat)));for(b=0;b<d.ingredients.length;b++)f+=Tb(g(d.ingredients[b]))+"\n";za.val(f);Aa.val(g(e.instructions.replace("\r","")));Ba.val(g(e.notes));x.dialog("option","title","Update Recipe");I.dialog(J);Ka.hide();La.show();Ma.hide();
""!==z&&wb(z,u.length,!0);h=ub();x.parent(".ui-dialog").css(C,y);x.dialog(ja,C,y);x.dialog(ka)}function Ub(){Na.show();Ia.unbind(O);Ja.unbind(O);a.post(ajaxurl,{action:"easyrecipeConvert",id:fb,type:Oa},Sb,"json")}function gb(d){var c,b,f=0,e="",k="",h="",g="",p=["instruction","method","cooking method","procedure","direction"];b=["ingredients?"];var m=["note","cooking note"],q,n;q=a.parseJSON(s.ingredients);n=a.parseJSON(s.instructions);c=a.parseJSON(s.notes);-1===a.inArray(q,b)&&b.push(q);q="^\\s*(?:"+
b.join("|")+")";q=new RegExp(q,"i");-1===a.inArray(n,p)&&b.push(n);p="^\\s*(?:"+p.join("|")+")";p=new RegExp(p,"i");-1===a.inArray(c,m)&&m.push(c);m="^\\s*(?:"+m.join("|")+")\\s*$";m=new RegExp(m,"i");d=a("<div>"+d+"</div>");d=tb(d[0].childNodes);d=d.split("\n");for(c=0;c<d.length;c++)if(b=a.trim(d[c]),""!==b)if(p.test(b))f=2;else if(q.test(b))f=1;else if(m.test(b))f=3;else switch(f){case 0:e+=b+"\n";break;case 1:k+=b+"\n";break;case 2:h+=b+"\n";break;case 3:g+=b+"\n"}return{summary:e,ingredients:k,
instructions:h,notes:g}}function Vb(d){var c,b=a(".easyrecipe",p),f=a("#divERSELRecipes").find("ul");f.empty();b.each(function(b){c=a(".ERName",this).text();""===c&&(c="Recipe "+(b+1));f.append(a("<li>"+c+"</li>").click(function(){U.dialog(J);xb(d,b)}))});U.parent(".ui-dialog").css(C,y);U.dialog(ja,C,y);U.dialog(ka)}function la(d,c,b){K.append('<div class="ERPhoto"><img style="position:relative" id="ERPhoto_'+c+'" /></div>');u[c]=a("#ERPhoto_"+c,K);u[c].data("src",d);b&&(a(".ERPhoto",K).removeClass(V),
u[c].parent().addClass(V),P=c,z=d);""===Pa&&(Pa=d);b=new Image;a.data(b,"index",c);b.onload=function(){var b,d,c=a.data(this,"index");b=this.width/150;d=this.height/112;b=b>d?b:d;d=Math.floor(this.height/b);b=Math.floor(this.width/b);u[c].height(d);u[c].width(b);u[c].css("top",(112-d)/2);u[c].attr("src",this.src);0===c&&a("#ERDTabs").find(".divERNoPhotos").remove()};b.src=d}function Wb(){la(hb.val(),u.length,!0);hb.val("");Qa.hide();a(".divERNoPhotos").remove()}function Ra(a,c){var b,f=!1;for(b=0;b<
u.length;b++)if(u[b].data("src")===a){f=!0;break}f||la(a,u.length,c)}function Ca(d,c){var b,f,e,k,t,l,m,n={},q=l="",w="";e="";if(!d||1===d.which)if(d&&d.data===Da&&(c=Da,d=d.delegateTarget),typeof c===na&&1<L)L=a(".easyrecipe",p).length,Vb(d);else{h=a(".easyrecipe",p);if(c===Da){for(k=0;k<h.length;k++)if(h[k]===d){fa=k;break}h=a(d)}typeof c===na&&typeof d===na&&(fa=0);c!==Sa&&1<h.length&&(h=a(h[c]),fa=c);k=a.support.cors?"json":"jsonp";a.ajax(Xb,{dataType:k,data:{v:s.version,p:1,u:s.wpurl},success:Qb,
error:Pb});ib=!1;typeof tinyMCE!==na&&tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden()&&(ib=!0);if(ib){R.val("");S.val("");$.val("");eb.val("");E.val("");T.val("");A.val("");B.val("");aa.val("");za.val("");Aa.val("");ga.val("");ha.val("");ia.val("");qa.val("");ra.val("");sa.val("");ta.val("");ua.val("");va.val("");wa.val("");xa.val("");ya.val("");Ba.val("");if(c!==Sa&&1===h.length)x.dialog("option","title","Update Recipe"),Ma.hide(),Ka.hide(),La.show(),jb=!0;else{Ta=H.getContent();if(!cb&&((k=
Yb.exec(Ta)||Zb.exec(Ta)||$b.exec(Ta))||(b=a("#hasRecipe").is(":checked")),k||b)){b?(Oa="recipress",fb=s.postID):(Oa=k[2],fb=k[3]);Na.hide();Ia.click(Rb);Ja.click(Ub);e=ac[Oa];l=a("#txtERCNVText1",I);l.html(l.html().replace("#plugin#",e));K.html("");P=-1;u=[];K.html(yb);I.parent(".ui-dialog").css(C,y);I.dialog(ja,C,y);I.dialog(ka);return}s.isGuest&&(k=a("#inpERAuthor").val()||"",E.val(k));Ka.show();La.hide();Ma.show();x.dialog("option","title","Add a New Recipe");jb=!1;!1!==Ua?n=gb(Ua):(k=H.selection.getContent(),
20<k.length&&(n=gb(k)));n.summary&&(l=n.summary);n.ingredients&&(q=n.ingredients);n.instructions&&(w=n.instructions);n.notes&&(e=n.notes);h=ub()}h.find(".hiddenGrammarError, .hiddenSpellError, .hiddenSuggestion").each(function(){var b;0<a(this).parent(".mceItemHidden").length&&a(this).unwrap();b=a(this).text();a(this).replaceWith(b)});n=h;h=a("<div>"+h.html()+"</div>");a("#inpERCuisine").autocomplete({source:a.parseJSON(s.cuisines)}).autocomplete("widget").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');
a("#inpERType").autocomplete({source:a.parseJSON(s.recipeTypes)}).autocomplete("widget").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');Y=!1;Ea.off("change",Za).on("change",Za);kb=!1;0<a(".hrecipe",p).length&&confirm("This post is already hrecipe microformatted\n\nDo you want me to try to convert it to an EasyRecipe?")&&(kb=!0);ma=c!==Sa?h.find(".endeasyrecipe").text():s.version;""===ma&&(ma="2.2");z=a('link[itemprop="image"]',h).attr("href")||"";K.html("");P=-1;Pa="";u=[];p.find("img").each(function(b){var c=
!1;"3">ma?a(this).hasClass("photo")&&(c=!0):c=this.src===z;la(this.src,b,c)});b=p.contents().text();k=zb.exec(b);for(m=u.length;null!==k;)f=bc.exec(k[0]),null!==f&&(f=f[1],la(f,m),"3"<ma?z===f&&(u[m].parent().addClass(V),P=m):cc.test(k[0])&&(u[m].parent().addClass(V),P=m,z=f),m++),k=zb.exec(b);""!==z&&Ra(z,!0);(Ab=a("#set-post-thumbnail").find("img").attr("src"))&&Ra(Ab,-1===P);-1===P&&0<u.length&&(P=0,z=Pa,u[0].parent().addClass(V));K.click(function(b){"IMG"===b.target.nodeName&&(a(".ERPhoto",K).removeClass(V),
a(b.target).parent().addClass(V),z=b.target.src)});0===u.length?K.html(yb):-1===P&&u[0].parent().addClass(V);Z=[];G=[];(k=h.find(".ERName .fn").html()||h.find(".ERName").html())&&""!==k?R.val(v(g(k))):R.val(v(g(a("#title").val())));S.val(v(g(h.find(".type").html())));E.val(v(g(h.find(".author").html())));""===E.val()&&E.val(v(a.parseJSON(s.author)));$.val(v(g(h.find(".cuisine").html())));T.val(v(l+g(h.find(".summary").html())));"3"<ma?(l=h.find('time[itemprop="prepTime"]').html()||"",A.val(g(l)),
l=h.find('time[itemprop="cookTime"]').html()||"",B.val(g(l))):(l=h.find(".preptime").html()||"",k=Bb.exec(l),null!==k?A.val(g(k[1])):A.val(""),l=h.find(".cooktime").html()||"",k=Bb.exec(l),null!==k?B.val(g(k[1])):B.val(""));aa.val(g(h.find(".yield").html()));h.find(".ingredients li").each(function(b,c){q=a(c).hasClass(Cb)?q+("!"+v(g(c.innerHTML))+"\n"):q+(v(g(c.innerHTML))+"\n")});za.val(q);h.find(".instructions li, .instructions .ERSeparator").each(function(b,c){t=a.trim(c.innerHTML.replace(/^[ 0-9.]*(.*)$/ig,
"$1"));w=a(c).hasClass(Cb)?w+("!"+t+"\n"):w+(t+"\n")});Aa.val(v(g(w)));ga.val(g(h.find(".servingSize").html()));ha.val(g(h.find(".calories").html()));ia.val(g(h.find(".fat").html()));qa.val(g(h.find(".saturatedFat").html()));ra.val(g(h.find(".unsaturatedFat").html()));sa.val(g(h.find(".transFat").html()));ta.val(g(h.find(".carbohydrates").html()));ua.val(g(h.find(".sugar").html()));va.val(g(h.find(".sodium").html()));wa.val(g(h.find(".fiber").html()));xa.val(g(h.find(".protein").html()));ya.val(g(h.find(".cholesterol").html()));
l=n.parent().prop("data-rating");pa.val(a.isNumeric(l)?l:"5");t=(g(h.find(".ERNotes").html())||"").replace(/<\/p>\n*<p>/ig,"\n\n").replace(/(?:<p>|<\/p>)/ig,"").replace(/<br *\/?>/ig,"\n");""===t&&""!==e&&(t=e);t=v(t);t=t.replace(/\[br(?: ?\/)?\]/ig,"\n");Ba.val(v(t));r&&(r.name&&R.val(v(g(r.name))),r.author&&E.val(v(r.author)),r.summary&&T.val(v(r.summary)),r.yield&&aa.val(g(r.yield)),r.type&&S.val(v(g(r.type))),r.cuisine&&$.val(v(g(r.cuisine))),r.prepTime&&A.val(g(r.prepTime)),r.cookTime&&B.val(g(r.cookTime)),
r.summary&&T.val(v(r.summary)));h=n;x.parent(".ui-dialog").css(C,y);x.dialog(ja,C,y);x.dialog(ka);x.dialog("option","position","center")}else alert("You must use the Visual Editor to add or update an EasyRecipe")}}function lb(d){L=a(".easyrecipe",p).length;dc||0===L?Ca(d,Sa):(mb.parent(".ui-dialog").css(C,y),mb.dialog(ja,C,y),mb.dialog(ka))}function ec(){x.dialog(J)}function fc(){U.dialog(J)}function gc(){confirm("Are you sure you want to delete this recipe?")&&(h.remove(),Y=h=!1);x.dialog(J)}function hc(){var d=
a("#inpERPaste"),c,b=d.val();c=gb(b);if(0!==c.ingredients.length||0!==c.instructions.length)Ua=b,d.val(""),r={name:w(ea(R.val())),author:w(n(E)),yield:n(aa),type:w(n(S)),cuisine:w(n($)),summary:w(n(T)),servesize:n(ga),prepTime:A.val(),cookTime:B.val()},Y=!1,x.dialog(J),lb(null)}function nb(d){d=a(d.target).parent();var c=d.parent();d.hasClass("easyrecipeAbove")?c.before(Db):c.after(Db);d.remove();Eb()}function Eb(){var d,c;c=a("<div>"+p[0].body.innerHTML+"</div>");c.find(".easyrecipeAbove,.easyrecipeBelow").remove();
d=c.find(".easyrecipe");d.each(function(){var b=a(this);b.parent().hasClass("easyrecipeWrapper")&&b.unwrap();Fb(b)});d=c.html();H.setContent(d);d=p.find(".easyrecipe");d.on("mousedown",null,Da,Ca);p.find(".ERInsertLine").on(O,nb)}function ic(a){var c,b;c=a.prev();b=a.next();if(c=0===c.length||c.hasClass("easyrecipe")||c.hasClass("easyrecipeWrapper"))try{c=!(a[0].previousSibling&&3===a[0].previousSibling.nodeType)}catch(f){}if(b=0===b.length||b.hasClass("easyrecipe")||b.hasClass("easyrecipeWrapper"))try{b=
!(a[0].nextSibling&&3===a[0].nextSibling.nodeType)}catch(e){}if(c||b)a.wrap('<div class="easyrecipeWrapper mceNonEditable" />'),a=a.parent(),c&&(a.prepend('<div class="easyrecipeAbove mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line above" /></div>'),a.find("input").on(O,nb),jc.push(a.find(".easyrecipeAbove")[0])),b&&(a.append('<div class="easyrecipeBelow mceNonEditable"><input class="ERInsertLine mceNonEditable" type="button" value="Insert line below" /></div>'),
a.find("input").on(O,nb))}function ob(){var d=a(".easyrecipe",p);0!==d.length&&(d.on("mousedown",null,Da,Ca),Eb())}function Gb(){var d,c="",b,f="",e=0,k="",g,l,r,u=[],q,v;if(Ga(A)&&Ga(B)){b=a.trim(A.val());""!==b?(m=ab.exec(b),g=m[1]?parseInt(m[1],10):0,l=m[2]?parseInt(m[2],10):0,e=60*g+l,f="PT"+(0<g?g+"H":"")+(0<l?l+"M":"")):b=!1;d=a.trim(B.val());""!==d?(m=ab.exec(d),g=m[1]?parseInt(m[1],10):0,l=m[2]?parseInt(m[2],10):0,e+=60*g+l,c="PT"+(0<g?g+"H":"")+(0<l?l+"M":"")):d=!1;0<e?(g=Math.floor(e/60),
l=e%60,e=0<g?g+" hour":"",1<g&&(e+="s"),k=0<l?l+" min":"",1<l&&(k+="s"),e=a.trim(e+" "+k),k="PT"+(0<g?g+"H":"")+(0<l?l+"M":"")):e=!1;g=za.val().split("\n");for(r=0;r<g.length;r++)l=g[r],""!==l&&("!"===l.charAt(0)?(q=!0,l=l.substr(1)):q=!1,u.push({ingredient:w(ea(l)),hasHeading:q}));g=Aa.val().split("\n");v=[];q={INSTRUCTIONS:[]};for(r=0;r<g.length;r++)l=a.trim(g[r].replace(/^[ 0-9\.]*(.*)$/ig,"$1")),""!==l&&("!"===l.charAt(0)?((0<q.INSTRUCTIONS.length||q.heading)&&v.push(q),l=l.substr(1),q={INSTRUCTIONS:[]},
q.heading=ea(l)):q.INSTRUCTIONS.push({instruction:w(ea(l))}));(0<q.INSTRUCTIONS.length||q.heading)&&v.push(q);(l=n(Ba))&&(l=l.replace(/\n/g,"[br]"));d={version:s.version,hasPhoto:""!==z,photoURL:z,name:w(ea(R.val())),author:w(n(E)),preptime:b,cooktime:d,totaltime:e,preptimeISO:f,cooktimeISO:c,totaltimeISO:k,yield:n(aa),type:w(n(S)),cuisine:w(n($)),summary:w(n(T)),servesize:n(ga),calories:n(ha),fat:n(ia),satfat:n(qa),unsatfat:n(ra),transfat:n(sa),carbs:n(ta),sugar:n(ua),sodium:n(va),fiber:n(wa),protein:n(xa),
cholesterol:n(ya),notes:w(l),rating:pa.length?pa.val():"0",INGREDIENTS:u,STEPS:v};""===d.name&&(d.name=!1);d=sb(s.recipeTemplate,d);kb&&a(".hrecipe",p).remove();-1===fa?h=a(bb,p):(h=a(".easyrecipe",p),0<h.length&&(h=a(h[fa])));h.before(d);h.remove();h=!1;ba.show();Y=!1;x.dialog(J);L=a(".easyrecipe",p).length;ob()}}function kc(d,c){var b,f;r=!1;if("3"<tinymce.majorVersion){if(c.id!==Q&&"wp_mce_fullscreen"!==c.id){a("#"+c.controlManager.buttons.easyrecipeTest._id).hide();a("#"+c.controlManager.buttons.easyrecipeEdit._id).hide();
a("#"+c.controlManager.buttons.easyrecipeAdd._id).hide();return}c.id===Q?(p=a("#"+Q+"_ifr").contents(),y=1E4,b=a("#"+c.controlManager.buttons.easyrecipeTest._id),ba=a("#"+c.controlManager.buttons.easyrecipeEdit._id)):(p=a("#wp_mce_fullscreen_ifr").contents(),y=200001,b=a("#mce_fullscreen_easyrecipeTest"),ba=a("#mce_fullscreen_easyrecipeEdit"))}else{if(c.editorId!==Q&&"wp_mce_fullscreen"!==c.editorId){a("#"+c.editorId+"_easyrecipeTest").hide();a("#"+c.editorId+"_easyrecipeEdit").hide();a("#"+c.editorId+
"_easyrecipeAdd").hide();return}c.editorId===Q?(p=a("#"+Q+"_ifr").contents(),y=1E4,b=a("#"+Q+"_easyrecipeTest"),ba=a("#"+Q+"_easyrecipeEdit")):(p=a("#wp_mce_fullscreen_ifr").contents(),y=200001,b=a("#mce_fullscreen_easyrecipeTest"),ba=a("#mce_fullscreen_easyrecipeEdit"))}oa=a("body",p);f=a(".easyrecipe",p);H=tinyMCE.activeEditor;f.each(function(){a(this).addClass("mceNonEditable");a(".ERRatingOuter",this).remove();a(".ERHDPrint",this).remove();a(".ERLinkback",this).remove()});L=f.length;0<L&&""!==
s.testURL?b.show():b.hide();0<L?ba.show():ba.hide();p.hasERCSS||(a("head",p).append('<link rel="stylesheet" type="text/css" href="'+s.easyrecipeURL+'/css/easyrecipe-entry.css" />'),p.hasERCSS=!0);ob()}function lc(){Hb.toggleClass("ERNone");pb.toggleClass("ERContract")}function mc(){Ib.toggleClass("ERNone");qb.toggleClass("ERContract")}function nc(d){var c;c=a("#ertmp_"+Va,p);G.push('href="'+d.href+'"'+(d.target?' target="'+d.target+'"':"")+(d.title?' title="'+d.title+'"':""));W.val(D.substring(0,
M)+"[url:"+G.length+"]"+D.substring(M,N)+"[/url]"+D.substring(N));W[0].focus();c.remove()}function oc(d){var c,b,f;s.isEntryDialog&&(c=a("#ertmp_"+Va,p),"string"===typeof d?b=a(d):(d=c.html(),"link"===d?c=b=c.parent("a"):b=a(c.html())),b.is("a")&&(d=b.attr("href"),f=b.attr("title"),b=b.attr("target"),d='href="'+d+'"'+(b?' target="'+b+'"':"")+(f?' title="'+f+'"':""),G.push(d),W.val(D.substring(0,M)+"[url:"+G.length+"]"+D.substring(M,N)+"[/url]"+D.substring(N))),W[0].focus(),c.remove())}function Wa(a,
c){var b,f,e,g,h;b=a.sizes[c.size];f=b.url;g=b.width;h=b.height;la(f,u.length);b=D.substring(0,M);Z.push('src="'+f+'" width="'+g+'" height="'+h+'"class="align'+c.align+'"');"none"===c.link?b+="[img:"+Z.length+"]":("file"===c.link?e=f:"post"===c.link?e=a.link:"custom"===c.link&&(e=c.linkUrl),G.push('href="'+e+'"'),b+="[url:"+G.length+"][img:"+Z.length+"][/url]");b+=D.substring(N);W.val(b);W[0].focus()}function pc(){var a;ca||(ca=wp.media({title:"Select Image",multiple:!1,library:{type:"image"},button:{text:"add image"}}),
ca.on("content:create:browse",function(c){a=c.view;c.view.options.display=!0}),ca.on("select",function(){var c=ca.state().get("selection"),b=a.sidebar.get("display").model.attributes;Wa(c.models[0].attributes,b)}),ca.$el.addClass("ui-dialog"));ca.open()}function qc(){var d,c=!1,b;F&&(F.focus(),M=F[0].selectionStart,N=F[0].selectionEnd,D=F.val(),d=a(this),d.hasClass("ERIconBold")?(c="[b]",b="[/b]"):d.hasClass("ERIconUnderline")?(c="[u]",b="[/u]"):d.hasClass("ERIconItalic")?(c="[i]",b="[/i]"):d.hasClass("ERIconLineBreak")&&
(c="[br]",b=""),c?(M===N&&""!==b||F.val(D.substring(0,M)+c+D.substring(M,N)+b+D.substring(N)),F[0].focus()):(d.hasClass("ERIconImage")&&(W=F,pc()),d.hasClass("ERIconLink")&&M!==N&&(W=F,Va++,d=a('<div class="erdeleteme" id="ertmp_'+Va+'">link</div>'),d.appendTo(oa),H.selection.select(d[0].firstChild),H.nodeChanged(),s.isGuest?s.doLink():(H.execCommand("WP_Link",!1),a("#wp-link-wrap").addClass("ui-dialog")))))}function rc(){r=!1;lb()}function sc(){r=!1;Ca()}function tc(){0<L&&!s.noHTMLWarn&&(s.noHTMLWarn=
!0,X.parent(".ui-dialog").css(C,y),X.dialog(ja,C,y),X.dialog(ka))}function uc(d){var c,b;if("dopreview"===a("#wp-preview",d.target).val()||0===L)return!0;(d=tinyMCE.activeEditor&&!tinyMCE.activeEditor.isHidden())?c=a("<div>"+H.getContent()+"</div>"):(b=a("#wp-content-editor-container").find("textarea"),c=a("<div>"+b.val()+"</div>"));var f=a(".easyrecipeWrapper",c);a(".easyrecipeAbove,.easyrecipeBelow",f).remove();a(".easyrecipe",f).unwrap();a(".easyrecipe",c).removeClass("mceNonEditable");c=a.trim(c.html());
d?H.setContent(c):b.val(c);return!0}function vc(d){var c,b,f,e;e=a("#easyrecipe-snippet").find(".ERRSP");f=e.find(".ERRSPStatus");d=a.parseJSON(d);d=a(d.html);c=d.find("#ires .vsc");0===c.length&&(c=d.find("#ires .rc"));0===c.length?(f.text("No snippet data returned from Google"),f.css("color","#f99")):(d=c.find("h3.r").text(),b=c.find(".s").html(),c=e.find(".ERRSPResult"),c.html("<h3>"+d+'</h3><div class="s">'+b+"</div>"),f.hide(),e.find(".ERRSPResult .f.slp .csb").css("background-image",""))}function wc(){}
function xc(d){""!=d.target.innerHTML&&(d=a(d.target).find("img").attr("src"))&&Ra(d,!1)}function yc(d){var c,b;d=d[0];for(c=0;c<d.addedNodes.length;c++)if(b=a(d.addedNodes[c].innerHTML),b=b.find("img").attr("src")){Ra(b,!1);break}}var Tb=jQuery.trim,H,ib,pa,R,T,za,Aa,A,B,aa,Q,E,S,$,eb,$a,cb=!1,kb,Ta,h,jb,Lb=/\x3c!-- START INCLUDEIF (!?)([_a-z][_0-9a-z]{0,19}) --\x3e/i,Mb=/^#([_a-z][_0-9a-z]{0,19})#/im,Nb=/\x3c!-- START REPEAT ([_a-zA-Z][_0-9a-zA-Z]{0,19}) --\x3e/m,Ab,Bb=/^([^<]*)/,ab=/^(?:([0-9]+) *(?:h|hr|hrs|hour|hours))? *(?:([0-9]+) *(?:m|mn|mns|min|mins|minute|minutes))?$/i,
Ob=/^([0-9]+)$/,Yb=/(.*)\[amd-(recipeseo|zlrecipe)-recipe:([0-9]+)\](.*)/,Zb=/(.*)\[(yumprint)-recipe\s+id='(\d+)'\](.*)/i,$b=/(.*)\[(gmc)_recipe\s+([0-9]+)\](.*)/,fb,Oa,db,xb,Ua,vb=/PT(?:([0-9]*)+H)?([0-9]+)+M/i,zb=/\[(?:img) +(?:[^\]]+?)\]/ig,cc=/class\s*=\s*"(?:[^"]+ )?photo[ "]/i,bc=/src\s*=\s*" *([^"]+?) *"/i,ac={recipeseo:"Recipe SEO",ziplist:"ZipList",zlrecipe:"ZipList",yumprint:"Yumprint Recipe Card",recipress:"ReciPress",gmc:"GetMeCooking"},G=[],Z=[],M,N,D,F=null,Va=0,W,s,X,Ha='<div class="easyrecipeholder">EasyRecipe</div>',
bb=".easyrecipeholder",Cb="ERSeparator",x,mb,U,I,p=null,oa,y,m,ja="option",C="zIndex",Fa,Xa,Ya,u,K,Ma,Na,Ia,Ja,Ka,La,Hb,pb,Ib,qb,ga,ha,ia,qa,ra,sa,ta,ua,va,wa,xa,ya,Ba,ba,L=0,fa,dc=!0,Qa,hb,P,rb,da,J="close",O="click",na="undefined",ka="open",V="ERPhotoSelected",Xb="http://www.easyrecipeplugin.com/checkUpdates.php",yb='<div class="divERNoPhotos">There are no photos in this post<br />Add photos anywhere in the post</div>',ma,Sa=-1,Da=-2,z="",Pa,Db="&nbsp;",Fb,wb,r,jc=[],Y=!1,Ea,ca;"use strict";a(function(){var d,
c;c=null;s=EASYRECIPE;s.button!==a.fn.button&&(c=a.fn.button,a.fn.button=s.button);x=a("#easyrecipeEntry");U=a("#easyrecipeSelect");X=a("#easyrecipeHTMLWarn");Q=s.isGuest?"guestpost":"content";U.dialog({autoOpen:!1,width:340,modal:!0,dialogClass:"easyrecipeSelect",close:function(){a(".easyrecipeSelect").filter(function(){return""===a(this).text()}).remove()},open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});a("#divERSELContainer").show();U.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');
x.dialog({autoOpen:!1,width:655,modal:!0,dialogClass:"easyrecipeEntry",beforeClose:function(){if(Y){if(!window.confirm("Are you sure you want to close without saving the recipe?"))return!1;Y=!1}return!0},close:function(){s.isEntryDialog=!1;h&&!jb&&h.remove();h=!1;a(".easyrecipeEntry").filter(function(){return""===a(this).text()}).remove()},open:function(){s.isEntryDialog=!0;a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');Fa.tabs({active:0,beforeActivate:Jb});setTimeout(function(){var b=
a(".easyrecipeEntry"),c=b.offset();c.top<rb&&(c.top=rb,b.offset(c))},250)}});x.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');Ea=a("#divERContainer").show();X.dialog({autoOpen:!1,width:420,modal:!0,dialogClass:"easyrecipeHTMLWarn",close:function(){a(".easyrecipeHTMLWarn").filter(function(){return""===a(this).text()}).remove()},open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});X.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');
a(".divERHTMLWarnContainer").show();I=a("#easyrecipeConvert");Na=a("#divERCNVSpinner");Ia=a("#btnERCNVCancel");Ja=a("#btnERCNVOK");Na.hide();I.dialog({autoOpen:!1,width:390,modal:!0,dialogClass:"easyrecipeConvert",close:function(){a(".easyrecipeConvert").filter(function(){return""===a(this).text()}).remove()},open:function(){a(".ui-widget-overlay").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />')}});a("#divERCNVContainer").show();I.parent(".ui-dialog").wrap('<div id="easyrecipeUI" class="easyrecipeUI" />');
a(window).bind("easyrecipeadd",rc);a(window).bind("easyrecipeedit",sc);a(window).bind("easyrecipeload",kc);a(window).bind("easyrecipeimage",Wa);a(window).bind("easyrecipeguestimageuploaded",Wa);Ya=a("#divERNext");Xa=a("#btnERButtons");Fa=a("#ERDTabs");K=a("#divERPhotos");a("input:submit",".easyrecipeUI").button();a("#ed_toolbar");pa=a("#inpERRating");R=a("#inpERName");E=a("#inpERAuthor");S=a("#inpERType");$=a("#inpERCuisine");eb=a("#inpERTags");T=a("textarea#taERSummary");za=a("textarea#taERIngredients");
Aa=a("textarea#taERInstructions");A=a("#inpERPrepTime");B=a("#inpERCookTime");aa=a("#inpERYield");ga=a("#inpERServeSize");ha=a("#inpERCalories");ia=a("#inpERFat");qa=a("#inpERSatFat");ra=a("#inpERUnsatFat");sa=a("#inpERTransFat");ta=a("#inpERCarbs");ua=a("#inpERSugar");va=a("#inpERSodium");wa=a("#inpERFiber");xa=a("#inpERProtein");ya=a("#inpERCholesterol");Ba=a("textarea#taERNotes");Qa=a("#divERAddImageURL");d=a("#lnkERPhotoURL");$a=a(".ERTimeError");Ka=a("#divERAdd");La=a("#divERChange");a("#divERHeader");
Hb=a("#divEROther");pb=a("#divEROtherLabel");Ib=a("#divERNotes");qb=a("#divERNotesLabel");Ma=a("#ERDPasteTab");hb=a("#fldERAPUImageURL");a("#btnERAdd").click(Gb);a("#btnERNext").click(Kb);a("#btnERChange").click(Gb);a("#btnERDelete").click(gc);a("#btnERCancel").click(ec);d.click(function(){Qa.show(500)});a("#btnERAIUCancel").click(function(){Qa.hide()});a("#btnERAIUOK").click(Wb);pb.click(lc);qb.click(mc);A.change(function(b){Ga(a(b.target))});B.change(function(b){Ga(a(b.target))});a("#btnERPaste").click(hc);
a("#btnERSELCancel").click(fc);rb=a("#wpadminbar").height();da=a("#divEREditBtns").on("mousedown","li",qc);Ea.find('input[type="text"], textarea').on("blur",function(){F=null}).on("focus",function(){F=a(this)});a("#wp-link").bind("wpdialogclose",oc);s.insertLink=nc;db=lb;xb=Ca;Ua=!1;s.insertUploadedImage=Wa;Fb=ic;wb=la;s.addListener=ob;X.find("input").on(O,function(){X.dialog(J)});a("#wp-content-editor-tools").on(O,"#content-html",tc);a("#post").on("submit",uc);null!==c&&(a.fn.button=c);d=a("#easyrecipe-snippet");
"none"!==d.css("display")&&(d=d.find(".ERRSPStatus").attr("postid"))&&a.ajax({url:ajaxurl,type:"POST",data:{action:"easyrecipeSnippet",id:d},success:vc,error:wc});d=a("#postimagediv").find(".inside");if(window.MutationObserver&&0<d.length)c=new MutationObserver(yc),c.observe(d[0],{childList:!0});else d.on("DOMSubtreeModified",xc);window.QTags&&QTags.addButton("easyrecipe","EasyRecipe",function(){alert("Switch to the Visual Editor to add or edit an EasyRecipe")},"","","",900)})})(jQuery);
